#!/bin/bash

# FIXME: -h option
# usage() {
#     cat <<EOM
# Usage: $(basename $0) filepath
# EOM
#     # exit 0
# }
# usage

FILE=$1
while read LINE; do
     echo "URL: $LINE"
     curl $LINE --silent | grep -Eo "(http|https)://www.instagram.com[a-zA-Z0-9./?=_-]*" | sort | uniq
done < $FILE
